spring:
  main:
      allow-circular-references: true
  jpa:
    hibernate:
      show_sql: true
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/characters
    username: mschitiva68
    password: Loquendo96@
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html
    operationsSorter: method
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days