spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      show_sql: true
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/characters
    username: root
    password: Loquendo96@
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8081
application:
  credentials:
    command:
      username: 'admin'
      password: 'sebas'
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 864000002 # a day
      refresh-token:
        expiration: 604800000 # 7 days

